pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label=ready-to-merge
      - label!=DNM
      - base=master
      - -draft
      - milestone=""
    actions:
      merge:
        method: merge
