name: Pull Request Review
on: pull_request_review
jobs:
  review:
    name: Add Reviewed-by Trailer
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Add Reviewed-by Trailer
        uses: epuertat/add-reviewed-by-action@916848f0135d3f33a25872fbfed500eac1dd8910
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          states: approved,commented
